services:
  - type: web
    name: ragchat
    runtime: python
    env: python
    region: singapore  
    plan: free  
    branch: main  
    rootDir: backend
    buildCommand: |
      export PIP_CACHE_DIR=/tmp/pip-cache
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: --prefer-binary -r requirements.txt || pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      # Python Version
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: GEMINI_API_KEY
        sync: false

      - key: QDRANT_URL
        sync: false

      - key: QDRANT_API_KEY
        sync: false

      - key: FRONTEND_URL
        sync: false

    healthCheckPath: /health
