services:
  - type: web
    name: ragchat
    runtime: python
    env: python
    region: singapore  
    plan: free  
    branch: main  
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      export CARGO_HOME=/tmp/cargo
      export RUSTUP_HOME=/tmp/rustup
      pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      # Python Version
      - key: PYTHON_VERSION
        value: 3.11.9

      # Rust/Cargo directories for packages that need compilation
      - key: CARGO_HOME
        value: /tmp/cargo

      - key: RUSTUP_HOME
        value: /tmp/rustup

      - key: GEMINI_API_KEY
        sync: false

      - key: QDRANT_URL
        sync: false

      - key: QDRANT_API_KEY
        sync: false

      - key: FRONTEND_URL
        sync: false

    healthCheckPath: /health
